module.exports = () => {
  return [
            {'nome': 'Arma +2', 'inicio': 1, 'fim': 11},
            {'nome': 'Estátua de poderes incríveis', 'inicio': 12, 'fim': 14},
            {'nome': 'Armadura de adamante (peitoral)', 'inicio': 15, 'fim': 15},
            {'nome': 'Armadura de adamante (cota de talas)', 'inicio': 16, 'fim': 16},
            {'nome': 'Amuleto de saúde', 'inicio': 17, 'fim': 17},
            {'nome': 'Armadura de vulnerabilidade', 'inicio': 18, 'fim': 18},
            {'nome': 'Escudo apanhador de flechas', 'inicio': 19, 'fim': 19},
            {'nome': 'Cinto dos anões', 'inicio': 20, 'fim': 20},
            {'nome': 'Cinturão de força do gigante da colina', 'inicio': 21, 'fim': 21},
            {'nome': 'Machado furioso', 'inicio': 22, 'fim': 22},
            {'nome': 'Botas de levitação', 'inicio': 23, 'fim': 23},
            {'nome': 'Botas de velocidade', 'inicio': 24, 'fim': 24},
            {'nome': 'Bacia de comandar elementais da água', 'inicio': 25, 'fim': 25},
            {'nome': 'Braceletes de defesa', 'inicio': 26, 'fim': 26},
            {'nome': 'Braseiro de comandar elementais do fogo', 'inicio': 27, 'fim': 27},
            {'nome': 'Capa do saltimbanco', 'inicio': 28, 'fim': 28},
            {'nome': 'Incensório de comandar elementais do ar', 'inicio': 29, 'fim': 29},
            {'nome': 'Cota de malha +1', 'inicio': 30, 'fim': 30},
            {'nome': 'Armadura de resistência (cota de malha)', 'inicio': 31, 'fim': 31},
            {'nome': 'Camisão de malha +1', 'inicio': 32, 'fim': 32},
            {'nome': 'Armadura de resistência (camisão de malha)', 'inicio': 33, 'fim': 33},
            {'nome': 'Manto do deslocamento', 'inicio': 34, 'fim': 34},
            {'nome': 'Manto do morcego', 'inicio': 35, 'fim': 35},
            {'nome': 'Cubo de força', 'inicio': 36, 'fim': 36},
            {'nome': 'Fortaleza instantânea de Daern', 'inicio': 37, 'fim': 37},
            {'nome': 'Adaga de envenenamento', 'inicio': 38, 'fim': 38},
            {'nome': 'Algemas dimensionais', 'inicio': 39, 'fim': 39},
            {'nome': 'Matadora de dragões', 'inicio': 40, 'fim': 40},
            {'nome': 'Malha élfica', 'inicio': 41, 'fim': 41},
            {'nome': 'Língua flamenjante', 'inicio': 42, 'fim': 42},
            {'nome': 'Gema de visão', 'inicio': 43, 'fim': 43},
            {'nome': 'Matador de gigantes', 'inicio': 44, 'fim': 44},
            {'nome': 'Couro batido encantador', 'inicio': 45, 'fim': 45},
            {'nome': 'Elmo de teletransporte', 'inicio': 46, 'fim': 46},
            {'nome': 'Trombeta de destruição', 'inicio': 47, 'fim': 47},
            {'nome': 'Trombeta de Valhalla (prata e latão)', 'inicio': 48, 'fim': 48},
            {'nome': 'Mandolim de Canaith', 'inicio': 49, 'fim': 49},
            {'nome': 'Lira de Cli', 'inicio': 50, 'fim': 50},
            {'nome': 'Pedra iônica (prontidão)', 'inicio': 51, 'fim': 51},
            {'nome': 'Pedra iônica (proteção)', 'inicio': 52, 'fim': 52},
            {'nome': 'Pedra iônica (armazenamento)', 'inicio': 53, 'fim': 53},
            {'nome': 'Pedra iônica (sustento)', 'inicio': 54, 'fim': 54},
            {'nome': 'Faixas de ferro de Bilarro', 'inicio': 55, 'fim': 55},
            {'nome': 'Armadura de couro +1', 'inicio': 56, 'fim': 56},
            {'nome': 'Armadura de resistência (couro)', 'inicio': 57, 'fim': 57},
            {'nome': 'Maça de rompimento', 'inicio': 58, 'fim': 58},
            {'nome': 'Maça de destruição', 'inicio': 59, 'fim': 59},
            {'nome': 'Maça do terror', 'inicio': 60, 'fim': 60},
            {'nome': 'Manto de resistência à magia', 'inicio': 61, 'fim': 61},
            {'nome': 'Corrente de contas de oração', 'inicio': 62, 'fim': 62},
            {'nome': 'Periapto de proteção contra veneno', 'inicio': 63, 'fim': 63},
            {'nome': 'Anel de cativar animais', 'inicio': 64, 'fim': 64},
            {'nome': 'Anel de evasão', 'inicio': 65, 'fim': 65},
            {'nome': 'Anel de queda suave', 'inicio': 66, 'fim': 66},
            {'nome': 'Anel de ação livre', 'inicio': 67, 'fim': 67},
            {'nome': 'Anel de proteção', 'inicio': 68, 'fim': 68},
            {'nome': 'Anel de resistência', 'inicio': 69, 'fim': 69},
            {'nome': 'Anel de armazenar magia', 'inicio': 70, 'fim': 70},
            {'nome': 'Anel do aríete', 'inicio': 71, 'fim': 71},
            {'nome': 'Anel de visão de raio-X', 'inicio': 72, 'fim': 72},
            {'nome': 'Robe dos olhos', 'inicio': 73, 'fim': 73},
            {'nome': 'Bastão da obediência', 'inicio': 74, 'fim': 74},
            {'nome': 'Bastão do guardião de pactos +2', 'inicio': 75, 'fim': 75},
            {'nome': 'Corda de estrangulamento', 'inicio': 76, 'fim': 76},
            {'nome': 'Brunea +1', 'inicio': 77, 'fim': 77},
            {'nome': 'Armadura de resistência (brunea)', 'inicio': 78, 'fim': 78},
            {'nome': 'Escudo +2', 'inicio': 79, 'fim': 79},
            {'nome': 'Escudo de atração de projéteis', 'inicio': 80, 'fim': 80},
            {'nome': 'Cajado de enfeitiçar', 'inicio': 81, 'fim': 81},
            {'nome': 'Cajado de cura', 'inicio': 82, 'fim': 82},
            {'nome': 'Cajado de enxame de insetos', 'inicio': 83, 'fim': 83},
            {'nome': 'Cajado das florestas', 'inicio': 84, 'fim': 84},
            {'nome': 'Cajado do definhamento', 'inicio': 85, 'fim': 85},
            {'nome': 'Pedra de comandar elementais da terra', 'inicio': 86, 'fim': 86},
            {'nome': 'Lâmina do sol', 'inicio': 87, 'fim': 87},
            {'nome': 'Espada do furto de vidas', 'inicio': 88, 'fim': 88},
            {'nome': 'Espada do sangramento', 'inicio': 89, 'fim': 89},
            {'nome': 'Bastão do tentáculo', 'inicio': 90, 'fim': 90},
            {'nome': 'Arma viciosa', 'inicio': 91, 'fim': 91},
            {'nome': 'Varinha de obrigação', 'inicio': 92, 'fim': 92},
            {'nome': 'Varinha de detecção de inimigos', 'inicio': 93, 'fim': 93},
            {'nome': 'Varinha de medo', 'inicio': 94, 'fim': 94},
            {'nome': 'Varinha de bolas de fogo', 'inicio': 95, 'fim': 95},
            {'nome': 'Varinha de relâmpagos', 'inicio': 96, 'fim': 96},
            {'nome': 'Varinha de paralisia', 'inicio': 97, 'fim': 97},
            {'nome': 'Varinha do arcano de guerra +2', 'inicio': 98, 'fim': 98},
            {'nome': 'Varina das maravilhas', 'inicio': 99, 'fim': 99},
            {'nome': 'Asas voadoras', 'inicio': 100, 'fim': 100}
          ]
}
