module.exports = () => {
  return [
            {'nome': 'Arma +1', 'inicio': 1, 'fim': 15},
            {'nome': 'Escudo +1', 'inicio': 16, 'fim': 18},
            {'nome': 'Escudo sentinela', 'inicio': 19, 'fim': 21},
            {'nome': 'Amuleto de proteção contra detecção e localização', 'inicio': 22, 'fim': 23},
            {'nome': 'Botas élficas', 'inicio': 24, 'fim': 25},
            {'nome': 'Botas de caminhar e saltar', 'inicio': 26, 'fim': 27},
            {'nome': 'Braçadeiras de arquearia', 'inicio': 28, 'fim': 29},
            {'nome': 'Broche do escudo', 'inicio': 30, 'fim': 31},
            {'nome': 'Vassoura voadora', 'inicio': 32, 'fim': 33},
            {'nome': 'Manto élfico', 'inicio': 34, 'fim': 35},
            {'nome': 'Manto de proteção', 'inicio': 36, 'fim': 37},
            {'nome': 'Manoplas de força do ogro', 'inicio': 39, 'fim': 40},
            {'nome': 'Chapéu de disfarce', 'inicio': 39, 'fim': 40},
            {'nome': 'Azagaia de relâmpago', 'inicio': 41, 'fim': 42},
            {'nome': 'Pérola do poder', 'inicio': 43, 'fim': 44},
            {'nome': 'Bastão do guardião de pactos +1', 'inicio': 46, 'fim': 47},
            {'nome': 'Chapéu de disfarce', 'inicio': 48, 'fim': 49},
            {'nome': 'Sandálias de patas de aranha', 'inicio': 50, 'fim': 51},
            {'nome': 'Cajado da víbora', 'inicio': 52, 'fim': 53},
            {'nome': 'Cajado da píton', 'inicio': 54, 'fim': 55},
            {'nome': 'Espada da vingança', 'inicio': 56, 'fim': 57},
            {'nome': 'Tridente de comandar peixes', 'inicio': 58, 'fim': 59},
            {'nome': 'Varinha de mísseis mágicos', 'inicio': 60, 'fim': 61},
            {'nome': 'Varinha do arcano de guerra +1', 'inicio': 62, 'fim': 63},
            {'nome': 'Varinha de teia', 'inicio': 64, 'fim': 65},
            {'nome': 'Arma de alerta', 'inicio': 66, 'fim': 67},
            {'nome': 'Armadura de adamante (cota de malha)', 'inicio': 45, 'fim': 45},
            {'nome': 'Armadura de adamante (camisão de malha)', 'inicio': 38, 'fim': 38},
            {'nome': 'Armadura de adamante (brunea)', 'inicio': 68, 'fim': 68},
            {'nome': 'Bolsa de truques (cinza)', 'inicio': 69, 'fim': 69},
            {'nome': 'Bolsa de truques (ferrugem)', 'inicio': 70, 'fim': 70},
            {'nome': 'Bolsa de truques (bronze)', 'inicio': 71, 'fim': 71},
            {'nome': 'Botas do inverno', 'inicio': 72, 'fim': 72},
            {'nome': 'Diadema da destruição', 'inicio': 73, 'fim': 73},
            {'nome': 'Baralho das ilusões', 'inicio': 74, 'fim': 74},
            {'nome': 'Garrafa de fumaça eterna', 'inicio': 75, 'fim': 75},
            {'nome': 'Olhos do encantamento', 'inicio': 76, 'fim': 76},
            {'nome': 'Olhos de águia', 'inicio': 77, 'fim': 77},
            {'nome': 'Estátua de poderes incríveis (corvo de prata)', 'inicio': 78, 'fim': 78},
            {'nome': 'Gema da luminosidade', 'inicio': 79, 'fim': 79},
            {'nome': 'Luvas de apanhar projéteis', 'inicio': 80, 'fim': 80},
            {'nome': 'Luvas de nadar e escalar', 'inicio': 81, 'fim': 81},
            {'nome': 'Luvas do ladrão', 'inicio': 82, 'fim': 82},
            {'nome': 'Tiara do intelecto', 'inicio': 83, 'fim': 83},
            {'nome': 'Elmo de telepatia', 'inicio': 84, 'fim': 84},
            {'nome': 'Alaúde de Doss', 'inicio': 85, 'fim': 85},
            {'nome': 'Bandolim de Fochlucan', 'inicio': 86, 'fim': 86},
            {'nome': 'Citara de Mac-Fuimidh', 'inicio': 87, 'fim': 87},
            {'nome': 'Medalha de pensamentos', 'inicio': 88, 'fim': 88},
            {'nome': 'Colar de adaptação', 'inicio': 89, 'fim': 89},
            {'nome': 'Periapto da cicatrização', 'inicio': 90, 'fim': 90},
            {'nome': 'Flauta assombrada', 'inicio': 91, 'fim': 91},
            {'nome': 'Flauta dos esgotos', 'inicio': 92, 'fim': 92},
            {'nome': 'Anel de saltar', 'inicio': 93, 'fim': 93},
            {'nome': 'Anel de escudo mental', 'inicio': 94, 'fim': 94},
            {'nome': 'Anel de calor', 'inicio': 95, 'fim': 95},
            {'nome': 'Anel de andar na água', 'inicio': 96, 'fim': 96},
            {'nome': 'Aljava de Ehlonna', 'inicio': 97, 'fim': 97},
            {'nome': 'Pedra da boa sorte', 'inicio': 98, 'fim': 98},
            {'nome': 'Leque do vento', 'inicio': 99, 'fim': 99},
            {'nome': 'Botas aladas', 'inicio': 100, 'fim': 100}
          ]
}
