module.exports = () => {
  return [
            {'nome': 'Poção de cura maior', 'inicio': 1, 'fim': 15},
            {'nome': 'Poção de sopro de fogo', 'inicio': 16, 'fim': 22},
            {'nome': 'Poção de resistência', 'inicio': 23, 'fim': 29},
            {'nome': 'Munição +1', 'inicio': 30, 'fim': 34},
            {'nome': 'Poção de amizade animal', 'inicio': 35, 'fim': 39},
            {'nome': 'Poção de força do gigante da colina', 'inicio': 40, 'fim': 44},
            {'nome': 'Poção de aumentar', 'inicio': 45, 'fim': 49},
            {'nome': 'Poção de respirar da água', 'inicio': 50, 'fim': 54},
            {'nome': 'Pergaminho de 2º nível', 'inicio': 55, 'fim': 59},
            {'nome': 'Pergaminho de 3º nível', 'inicio': 60, 'fim': 64},
            {'nome': 'Mochila de carga', 'inicio': 65, 'fim': 67},
            {'nome': 'Unguento de Keoghtom', 'inicio': 68, 'fim': 70},
            {'nome': 'Óleo escorregadio', 'inicio': 71, 'fim': 73},
            {'nome': 'Pó do desaparecimento', 'inicio': 74, 'fim': 75},
            {'nome': 'Pó da seca', 'inicio': 76, 'fim': 77},
            {'nome': 'Pó de espirrar e tossir', 'inicio': 78, 'fim': 79},
            {'nome': 'Gema elemental', 'inicio': 80, 'fim': 81},
            {'nome': 'Filtro do amor', 'inicio': 82, 'fim': 83},
            {'nome': 'Jarro de alquimia', 'inicio': 84, 'fim': 84},
            {'nome': 'Capa de respirar na água', 'inicio': 85, 'fim': 85},
            {'nome': 'Manto da arraia', 'inicio': 86, 'fim': 86},
            {'nome': 'Globo de fluxo', 'inicio': 87, 'fim': 87},
            {'nome': 'Óculos noturnos', 'inicio': 88, 'fim': 88},
            {'nome': 'Elmo de compreensão de idiomas', 'inicio': 89, 'fim': 89},
            {'nome': 'Bastão imóvel', 'inicio': 90, 'fim': 90},
            {'nome': 'Lanterna de revelação', 'inicio': 91, 'fim': 91},
            {'nome': 'Armadura do marinheiro', 'inicio': 92, 'fim': 92},
            {'nome': 'Armadura de mitral', 'inicio': 93, 'fim': 93},
            {'nome': 'Poção de envenenamento', 'inicio': 94, 'fim': 94},
            {'nome': 'Anel de natação', 'inicio': 95, 'fim': 95},
            {'nome': 'Robe dos itens úteis', 'inicio': 96, 'fim': 96},
            {'nome': 'Corda de escalada', 'inicio': 97, 'fim': 97},
            {'nome': 'Sela do cavaleiro', 'inicio': 98, 'fim': 98},
            {'nome': 'Varinha de detectar magia', 'inicio': 99, 'fim': 99},
            {'nome': 'Varinha de segredos', 'inicio': 100, 'fim': 100}
            
          ]
}
