module.exports = () => {
  return [
    {'nome': 'Arma +3', 'inicio': 1, 'fim': 10},
    {'nome': 'Amuleto dos planos', 'inicio': 11, 'fim': 12},
    {'nome': 'Tapete voador', 'inicio': 13, 'fim': 14},
    {'nome': 'Bola de cristal (versão muito rara)', 'inicio': 15, 'fim': 16},
    {'nome': 'Anel de regeneração', 'inicio': 17, 'fim': 18},
    {'nome': 'Anel de estrelas cadentes', 'inicio': 19, 'fim': 20},
    {'nome': 'Anel de telecinésia', 'inicio': 21, 'fim': 22},
    {'nome': 'Robe das cores cintilantes', 'inicio': 23, 'fim': 24},
    {'nome': 'Robe das estrelas', 'inicio': 25, 'fim': 26},
    {'nome': 'Bastão de absorção', 'inicio': 27, 'fim': 28},
    {'nome': 'Bastão de prontidão', 'inicio': 29, 'fim': 30},
    {'nome': 'Bastão de segurança', 'inicio': 31, 'fim': 32},
    {'nome': 'Bastão guardião de pactos +3', 'inicio': 33, 'fim': 34},
    {'nome': 'Cimitarra da velocidade', 'inicio': 35, 'fim': 36},
    {'nome': 'Escudo +3', 'inicio': 37, 'fim': 38},
    {'nome': 'Cajado de fogo', 'inicio': 39, 'fim': 40},
    {'nome': 'Cajado de frio', 'inicio': 41, 'fim': 42},
    {'nome': 'Cajado do poder', 'inicio': 43, 'fim': 44},
    {'nome': 'Cajado de ataque', 'inicio': 45, 'fim': 46},
    {'nome': 'Cajado de trovão e relâmpago', 'inicio': 47, 'fim': 48},
    {'nome': 'Espada decepadora', 'inicio': 49, 'fim': 50},
    {'nome': 'Varinha de metamorfose', 'inicio': 51, 'fim': 52},
    {'nome': 'Varinha do arcano de guerra +3', 'inicio': 53, 'fim': 54},
    {'nome': 'Armadura de adamante (meia-armadura)', 'inicio': 55, 'fim': 55},
    {'nome': 'Armadura de adamante (placas)', 'inicio': 56, 'fim': 56},
    {'nome': 'Escudo animado', 'inicio': 57, 'fim': 57},
    {'nome': 'Cinturão de força do gigante do fogo', 'inicio': 58, 'fim': 58},
    {'nome': 'Cinturão de força do gigante do frio', 'inicio': 59, 'fim': 59},
    {'nome': 'Peitoral +1', 'inicio': 60, 'fim': 60},
    {'nome': 'Armadura de resistência (peitoral)', 'inicio': 61, 'fim': 61},
    {'nome': 'Vela de invocação', 'inicio': 62, 'fim': 62},
    {'nome': 'Cota de malha +2', 'inicio': 63, 'fim': 63},
    {'nome': 'Camisão de malha +2', 'inicio': 64, 'fim': 64},
    {'nome': 'Manto da aranha', 'inicio': 65, 'fim': 65},
    {'nome': 'Espada dançarina', 'inicio': 66, 'fim': 66},
    {'nome': 'Armadura demoníaca', 'inicio': 67, 'fim': 67},
    {'nome': 'Brunea de escamas de dragão', 'inicio': 68, 'fim': 68},
    {'nome': 'Armadura anã', 'inicio': 69, 'fim': 69},
    {'nome': 'Arremessador anão', 'inicio': 70, 'fim': 70},
    {'nome': 'Garrafa de efreeti', 'inicio': 71, 'fim': 71},
    {'nome': 'Estátua de poderes incríveis (corcel de obsidiana)', 'inicio': 72, 'fim': 72},
    {'nome': 'Marca congelante', 'inicio': 73, 'fim': 73},
    {'nome': 'Elmo briliante', 'inicio': 74, 'fim': 74},
    {'nome': 'Trombeta de Valhalla (bronze)', 'inicio': 75, 'fim': 75},
    {'nome': 'Harpa de Anstruth', 'inicio': 76, 'fim': 76},
    {'nome': 'Pedra Iônica (absorção)', 'inicio': 77, 'fim': 77},
    {'nome': 'Pedra Iônica (agilidade)', 'inicio': 78, 'fim': 78},
    {'nome': 'Pedra Iônica (fortitude)', 'inicio': 79, 'fim': 79},
    {'nome': 'Pedra Iônica (intuição)', 'inicio': 80, 'fim': 80},
    {'nome': 'Pedra Iônica (intelecto)', 'inicio': 81, 'fim': 81},
    {'nome': 'Pedra Iônica (liderança)', 'inicio': 82, 'fim': 82},
    {'nome': 'Pedra Iônica (força)', 'inicio': 83, 'fim': 83},
    {'nome': 'Armadura de couro +2', 'inicio': 84, 'fim': 84},
    {'nome': 'Manual da saúde corporal', 'inicio': 85, 'fim': 85},
    {'nome': 'Manual do bom exercício', 'inicio': 86, 'fim': 86},
    {'nome': 'Manual dos golens', 'inicio': 87, 'fim': 87},
    {'nome': 'Manual da rapidez de movimentos', 'inicio': 88, 'fim': 88},
    {'nome': 'Espelho do aprisionamento', 'inicio': 89, 'fim': 89},
    {'nome': 'Ladra das nove vidas', 'inicio': 90, 'fim': 90},
    {'nome': 'Arco do juramento', 'inicio': 91, 'fim': 91},
    {'nome': 'Brunea +2', 'inicio': 92, 'fim': 92},
    {'nome': 'Escudo de proteção contra magia', 'inicio': 93, 'fim': 93},
    {'nome': 'Cota de talas +1', 'inicio': 94, 'fim': 94},
    {'nome': 'Armadura de resistência (cota de talas)', 'inicio': 95, 'fim': 95},
    {'nome': 'Armadura de couro batido +1', 'inicio': 96, 'fim': 96},
    {'nome': 'Armadura de resistência (couro batido)', 'inicio': 97, 'fim': 97},
    {'nome': 'Tomo dos grandes pensamentos', 'inicio': 98, 'fim': 98},
    {'nome': 'Tomo de liderança e influência', 'inicio': 99, 'fim': 99},
    {'nome': 'Tomo da compreensão', 'inicio': 100, 'fim': 100}
  ]
}
